// Generated by gencpp from file bridge-px4/GcsCmd.msg
// DO NOT EDIT!


#ifndef BRIDGE-PX4_MESSAGE_GCSCMD_H
#define BRIDGE-PX4_MESSAGE_GCSCMD_H

#include <ros/service_traits.h>


#include <bridge-px4/GcsCmdRequest.h>
#include <bridge-px4/GcsCmdResponse.h>


namespace bridge-px4
{

struct GcsCmd
{

typedef GcsCmdRequest Request;
typedef GcsCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GcsCmd
} // namespace bridge-px4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bridge-px4::GcsCmd > {
  static const char* value()
  {
    return "036b31736abf2284d72b9d0bf32bb22a";
  }

  static const char* value(const ::bridge-px4::GcsCmd&) { return value(); }
};

template<>
struct DataType< ::bridge-px4::GcsCmd > {
  static const char* value()
  {
    return "bridge-px4/GcsCmd";
  }

  static const char* value(const ::bridge-px4::GcsCmd&) { return value(); }
};


// service_traits::MD5Sum< ::bridge-px4::GcsCmdRequest> should match
// service_traits::MD5Sum< ::bridge-px4::GcsCmd >
template<>
struct MD5Sum< ::bridge-px4::GcsCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bridge-px4::GcsCmd >::value();
  }
  static const char* value(const ::bridge-px4::GcsCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bridge-px4::GcsCmdRequest> should match
// service_traits::DataType< ::bridge-px4::GcsCmd >
template<>
struct DataType< ::bridge-px4::GcsCmdRequest>
{
  static const char* value()
  {
    return DataType< ::bridge-px4::GcsCmd >::value();
  }
  static const char* value(const ::bridge-px4::GcsCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bridge-px4::GcsCmdResponse> should match
// service_traits::MD5Sum< ::bridge-px4::GcsCmd >
template<>
struct MD5Sum< ::bridge-px4::GcsCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bridge-px4::GcsCmd >::value();
  }
  static const char* value(const ::bridge-px4::GcsCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bridge-px4::GcsCmdResponse> should match
// service_traits::DataType< ::bridge-px4::GcsCmd >
template<>
struct DataType< ::bridge-px4::GcsCmdResponse>
{
  static const char* value()
  {
    return DataType< ::bridge-px4::GcsCmd >::value();
  }
  static const char* value(const ::bridge-px4::GcsCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BRIDGE-PX4_MESSAGE_GCSCMD_H
